Audio stuff, but not necessary.

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -60,6 +60,9 @@ sudo aptitude update && sudo aptitude upgrade -y
 echo "Installing the majority of the packages."
 sudo aptitude install -y acpi atom feh git git-extras google-chrome-stable gpointing-device-settings gtk-chtheme htop ibam locate lxappearance numlockx oracle-java8-installer oracle-java8-set-default python-stdeb qt4-qtconfig scrot texlive-full traceroute wget xautolock xbacklight zsh
 
+echo "Attempting to install audio utilities, not a big deal if this fails."
+sudo aptitude install -y pulseaudio-utils || :
+
 #
 # Some weird stuff to get i3 set up
 #
