Expanded boostrap for new packages, server/laptop support.

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -3,6 +3,44 @@
 # Install all the needed things for our system
 #
 
+#
+# Figure out if we're doing a server/laptop install, and if we want tex
+#
+
+isLaptop=0
+installTex=0
+
+while [[ $# -gt 1 ]]; do
+    key="$1"
+    case $key in
+        -l|--laptop)
+            isLaptop=1
+            ;;
+        -t|--tex|--latex)
+            installTex=1
+            ;;
+    esac
+    
+    shift
+done
+
+echo -n "Installing "
+if [ $isLaptop -eq 1 ]; then
+    echo -n "a LAPTOP/INTERACTIVE system"
+else
+    echo -n "a SERVER system"
+fi
+
+if [ $installTex -eq 1 ]; then
+    echo -n " with Tex/Latex support"
+fi
+
+echo "."
+
+#
+# Need root access
+#
+
 if [ "$(id -u)" == "0" ]; then
 	echo "This file must NOT be run by root." 1>&2
 	exit 1
@@ -42,6 +80,12 @@ sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /et
 # Atom
 sudo add-apt-repository -y ppa:webupd8team/atom
 
+# Wine
+sudo add-apt-repository -y ppa:ubuntu-wine/ppa
+
+# Wireshark (just the repo, don't install it yet)
+sudo apt-add-repository ppa:wireshark-dev/stable
+
 # Oracle Java
 sudo add-apt-repository -y ppa:webupd8team/java
 
@@ -52,17 +96,8 @@ sudo add-apt-repository -y ppa:git-core/ppa
 sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
 echo "deb https://apt.dockerproject.org/repo ubuntu-`lsb_release -cs` main" | sudo tee /etc/apt/sources.list.d/docker.list
 
-# NodeJS
-echo "deb https://deb.nodesource.com/node_6.x xenial main\ndeb-src https://deb.nodesource.com/node_6.x xenial main" | sudo tee /etc/apt/sources.list.d/nodesource.list
-
-# Wine
-sudo add-apt-repository -y ppa:ubuntu-wine/ppa
-
 # Asciinema
 sudo apt-add-repository ppa:zanchey/asciinema
-
-# Wireshark (just the repo, don't install it yet)
-sudo apt-add-repository ppa:wireshark-dev/stable
 
 # TexLive (latex)
 sudo add-apt-repository ppa:jonathonf/texlive-2017
@@ -76,7 +111,7 @@ sudo aptitude update && sudo aptitude upgrade -y
 #
 # Here's the big chuck of packages
 #
-echo "Installing the majority of the packages."
+echo "Installing the majority of the CLI/Serve/Backend packages."
 sudo aptitude install -y \
         acpi \
         asciinema \
@@ -84,29 +119,23 @@ sudo aptitude install -y \
         apt-transport-https \
         ansiweather \
         antiword \
-        atom \
         build-essential \
         bzip2 \
         ca-certificates \
+        datamash \
         docker-engine \
         entr \
-        feh \
         fortune-mod \
-        gimp \
         git \
         git-extras \
-        google-chrome-stable \
         gpointing-device-settings \
         gtk-chtheme \
-        guake \
         htop \
-        ibam \
         inotify-tools \
         inxi \
         locate \
-        lxappearance \
-        nodejs \
-        numlockx \
+        lynx \
+        openjdk-8-jre \
         oracle-java8-installer \
         oracle-java8-set-default \
         pandoc \
@@ -116,37 +145,56 @@ sudo aptitude install -y \
         python3-pip \
         python-setuptools \
         python-stdeb \
-        qt4-qtconfig \
-        screen \
-        scrot \
+        silversearcher-ag \
         taskwarrior \
-        texlive-full \
         tmux \
         traceroute \
         vim \
-        wine \
         wget \
-        xautolock \
-        xbacklight \
-        xclip \
-        xdot \
         xindy \
         zsh
 
-echo "Attempting to install audio utilities, not a big deal if this fails."
-sudo aptitude install -y pulseaudio-utils || :
+if [ $isLaptop -eq 1 ]; then
+    echo "Installing laptop-focused packages."
+    sudo aptitude install -y \
+            atom \
+            feh \
+            gimp \
+            google-chrome-stable \
+            guake \
+            ibam \
+            lxappearance \
+            numlockx \
+            qt4-qtconfig \
+            scrot \
+            wine \
+            xautolock \
+            xbacklight \
+            xclip \
+            xdot
 
-#
-# Some weird stuff to get i3 set up
-#
-echo "Trying to get i3 up and running."
-sudo sh -c 'echo "deb http://debian.sur5r.net/i3/ $(lsb_release -c -s) universe" >> /etc/apt/sources.list.d/i3.list'
-sudo apt-get update
-sudo apt-get --allow-unauthenticated install sur5r-keyring
-sudo apt-get update
-sudo apt-get install -y \
-        i3 \
-        suckless-tools
+    echo "Attempting to install audio utilities, not a big deal if this fails."
+    sudo aptitude install -y pulseaudio-utils || :
+fi
+
+if [ $installTex -eq 1 ]; then
+    echo "Attempting to install texlive, not a big deal if this fails.  And you may not even want this."
+    sudo aptitude install -y texlive-full || :
+fi
+
+if [ $isLaptop -eq 1 ]; then
+    #
+    # Some weird stuff to get i3 set up
+    #
+    echo "Trying to get i3 up and running."
+    sudo sh -c 'echo "deb http://debian.sur5r.net/i3/ $(lsb_release -c -s) universe" >> /etc/apt/sources.list.d/i3.list'
+    sudo apt-get update
+    sudo apt-get --allow-unauthenticated install sur5r-keyring
+    sudo apt-get update
+    sudo apt-get install -y \
+            i3 \
+            suckless-tools
+fi
 
 #
 # Download and install our shell
@@ -157,10 +205,12 @@ cd ~/.cahhome/modules && git clone git@bitbucket.org:cheilman/cahhome_atom.git a
 
 cd ~ && ./.cahhome/install
 
-#
-# Install py3status
-#
-cd ~/.i3/dev-py3status && sudo pypi-install py3status
+if [ $isLaptop -eq 1 ]; then
+    #
+    # Install py3status
+    #
+    cd ~/.i3/dev-py3status && sudo pypi-install py3status
+fi
 
 #
 # Switch to zsh
